### PR TITLE
Feature/reader cond

### PR DESCRIPTION
**Pull request by nha**
Related: https://github.com/venantius/yagni/pull/39

### CODE REVIEW

**Comment by venantius** [comment]
Could we add a test that explicitly checks a reader conditional form? It doesn't look like one is currently part of this PR.

**Comment by nha** [comment]
@venantius added tests - they pass locally but for some reason fail on Travis - not familiar with Travis -  any idea why that would be?

```
Could not transfer artifact org.clojure:clojure:jar:1.9.0 from/to central (https://repo1.maven.org/maven2/): Access denied to: https://repo1.maven.org/maven2/org/clojure/clojure/1.9.0/clojure-1.9.0.jar , ReasonPhrase:Forbidden.
Could not find artifact org.clojure:clojure:jar:1.9.0 in clojars (https://repo.clojars.org/)
Could not transfer artifact org.clojure:tools.logging:jar:0.4.0 from/to central (https://repo1.maven.org/maven2/): Access denied to: https://repo1.maven.org/maven2/org/clojure/tools.logging/0.4.0/tools.logging-0.4.0.jar , ReasonPhrase:Forbidden.
Could not find artifact org.clojure:tools.logging:jar:0.4.0 in clojars (https://repo.clojars.org/)
Could not transfer artifact org.clojure:tools.namespace:jar:0.2.11 from/to central (https://repo1.maven.org/maven2/): Access denied to: https://repo1.maven.org/maven2/org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11.jar , ReasonPhrase:Forbidden.
```

**Comment by venantius** [comment]
Seems to be a temporary Travis-related failure, not an actual fault with your work. Let's try the fix proposed here: https://github.com/diffblue/cbmc/pull/2863 - either way I'm guessing tests will pass in a day or two once Travis has a chance to fix their shit.

**Comment by nha** [comment]
@venantius PTAL, I made an extra commit to kick the build, it passes now

**Comment by venantius** [comment]
Great, thanks for this! I'll cut a new release now.

**Comment by venantius** [comment]
Ahaha, I totally ignored that commit with changelog details and just bumped the version a second time. Oh well. It's out now as 0.1.6. Whoops!

**Pull request merged**
