### PR TITLE
Allow conditional read

### LINKED ISSUE #37: Conditional read not allowed
Looks like yagni is choking on conditionals in cljc files. This isn't a CLJS project, as it's running on the JVM, but it shares code with someone that runs on CLJS. I know there's #26, but it seems like this could be solved without actually supporting CLJS, since it's more an issue of handling the reader conditional.

### PR DESCRIPTION
**Pull request by tomconnors**
Fixes #37

### CODE REVIEW

**Comment by venantius** [comment]
I think tests may need updating here.

**Comment by jcf** [comment]
I've fixed the tests in my branch: https://github.com/jcf/yagni/tree/2018-update

**Comment by venantius** [comment]
@jcf I'm open to a direct PR from you since you fixed it.

**Comment by nha** [comment]
@jcf mind opening a PR? that would be a welcome update 🥇

**Comment by venantius** [comment]
Closing this in favor of #43

**Pull request closed without merging**
